# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='neighbourhood_id',
        ),
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
