# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 06:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_auto_20190325_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='neighbourhood',
        ),
        migrations.AlterField(
            model_name='business',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
