# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0008_auto_20190325_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood')),
            ],
        ),
    ]
