# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbour', '0011_auto_20190325_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('profile', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
