# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0012_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
