# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0013_business_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='neighbour',
        ),
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
