# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbour', '0014_auto_20190325_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('img', models.ImageField(upload_to='images')),
                ('email', models.EmailField(max_length=254)),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
