# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0016_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='evenname',
            new_name='eventname',
        ),
    ]
