# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0017_auto_20190325_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Events',
        ),
    ]
