# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0020_auto_20190325_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='img',
            field=models.ImageField(upload_to='business'),
        ),
    ]
