# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0022_contacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbour.Neighbourhood'),
        ),
    ]
